# Generated by Django 4.2.16 on 2024-09-19 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_preserve_quantity_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='reserved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
