# Generated by Django 4.2.16 on 2024-09-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_myreservation'),
        ('product', '0002_preserve_quantity_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.myreservation'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Reserved'), (2, 'Sold')], default=0),
        ),
    ]
