# Generated by Django 4.2.16 on 2024-09-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_myreservation'),
        ('product', '0003_stockitem_reservation_alter_stockitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='reservation.myreservation'),
        ),
    ]
