# Generated by Django 4.2.16 on 2024-09-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_stockitem_reserved_by_stockitem_reserved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='reserved_note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Reserved'), (2, 'Sold')], default=0),
        ),
    ]
