# Generated by Django 4.2.16 on 2024-09-29 08:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_stockitem_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
