# Generated by Django 4.2.16 on 2024-09-23 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyReservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserved_note', models.CharField(blank=True, max_length=100)),
                ('reserved_date', models.DateField(blank=True, null=True)),
                ('reservation_complete', models.IntegerField(choices=[(0, 'Started'), (1, 'Complete')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
