# Generated by Django 4.2.16 on 2024-10-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_myreservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='ReservationPage',
        ),
        migrations.AlterField(
            model_name='myreservation',
            name='reservation_complete',
            field=models.IntegerField(choices=[(0, 'Started'), (1, 'Reserved'), (2, 'Complete')], default=0),
        ),
    ]
